export { accountCreatedTemplate } from './account-created.template';
export { deliveryAssignedTemplate } from './delivery-assigned.template';
export { orderConfirmedTemplate } from './order-confirmed.template';
export { orderDeliveredTemplate } from './order-delivered.template';
export { orderStatusChangedTemplate } from './order-status-changed.template';
export { passwordChangedTemplate } from './password-changed.template';
export { restaurantOrderConfirmedTemplate } from './restaurant-order-confirmed.template';
export { resetPasswordTemplate } from './reset-password.template';
export { menuItemAvailableTemplate } from './menu-item-available.template';
